### ISSUE TITLE
`no_std` support

### ISSUE THREAD

**Issue by quininer** [selfup/stringer#1]

**Comment by selfup** [comment]
Could you give me a description?

It would be quite difficult to make this work without the std lib.

I'll look into it!

**Comment by selfup** [comment]
### I added a CONTRIBUTING guideline and an ISSUE_TEMPLATE.
- I will close this issue and accept a new one that follows the new rules.
- Thanks for wanting to contribute! 
- Sorry for closing this, but I need to know why a feature request is not a pull request!
